<?php

namespace ContainerAGTuYoM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_F8jRuY5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.f8jRuY5' shared service.
     *
     * @return \App\Controller\ValidateSevice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TheMainController::form()": the $validator argument is type-hinted with the non-existent class or interface: "App\\Controller\\ValidateSevice". Did you forget to add a use statement?');
    }
}
