<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCmcQbuJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCmcQbuJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCmcQbuJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCmcQbuJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCmcQbuJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CmcQbuJ',
    'container.build_id' => '59b80bef',
    'container.build_time' => 1659431284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCmcQbuJ');
