<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_circle' => [['radius'], ['radius' => null, '_controller' => 'App\\Controller\\CircleController::calculateSurface'], [], [['variable', '/', '[^/]++', 'radius', true], ['text', '/circle']], [], [], []],
    'circle_double_controlller' => [['radius', 'radius2'], ['radius' => null, 'radius2' => null, '_controller' => 'App\\Controller\\CircleDoubleController::calculateSurface'], [], [['variable', '/', '[^/]++', 'radius2', true], ['variable', '/', '[^/]++', 'radius', true], ['text', '/doublecircle']], [], [], []],
    'app_testings' => [[], ['_controller' => 'App\\Controller\\TestingsController::index'], [], [['text', '/testings']], [], [], []],
    'app_the_main' => [[], ['_controller' => 'App\\Controller\\TheMainController::index'], [], [['text', '/']], [], [], []],
    'app_triangle' => [['a', 'b', 'c'], ['a' => null, 'b' => null, 'c' => null, '_controller' => 'App\\Controller\\TriangleController::doubletriangle'], [], [['variable', '/', '[^/]++', 'c', true], ['variable', '/', '[^/]++', 'b', true], ['variable', '/', '[^/]++', 'a', true], ['text', '/triangle']], [], [], []],
    'triangle' => [['a', 'b', 'c', 'd', 'e', 'f'], ['a' => null, 'b' => null, 'c' => null, 'd' => null, 'e' => null, 'f' => null, '_controller' => 'App\\Controller\\TriangleDoubleController::triangle'], [], [['variable', '/', '[^/]++', 'f', true], ['variable', '/', '[^/]++', 'e', true], ['variable', '/', '[^/]++', 'd', true], ['variable', '/', '[^/]++', 'c', true], ['variable', '/', '[^/]++', 'b', true], ['variable', '/', '[^/]++', 'a', true], ['text', '/doubletriangle']], [], [], []],
];
